@DotNet9EFAPI_HostAddress = http://localhost:5048

GET {{DotNet9EFAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{DotNet9EFAPI_HostAddress}}/api/v1/test/get/all/items
Accept: application/json

###
