@DotNet9EFAPI_HostAddress = http://localhost:5048

GET {{DotNet9EFAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{DotNet9EFAPI_HostAddress}}/api/v1/test/get/all/items
Accept: application/json

###
POST {{DotNet9EFAPI_HostAddress}}/api/v1/test/user/register/user
Content-Type: application/json
Accept: application/json

{
  "user": {
    "userName": "kevin4.vo",
    "email": "kevin.vo4@example.com",
    "passwordHash": "Str0ngP@ssword1231!",
    "firstName": "Kevin",
    "lastName": "Vo",
    "phoneNumber": "555-123-4567"
  }
}